In [31]:
from fractions import Fraction
from copy import deepcopy

def read_matrix():
    print("Digite a matriz linha por linha (somente números).")
    print("Exemplo:")
    print("1 2 3")
    print("0 1 4")
    print("5 6 0")
    print("Pressione ENTER em branco para terminar.\n")

    matrix = []
    while True:
        line = input("Linha: ").strip()
        if line == "":
            break
        row = [Fraction(x) for x in line.split()]
        matrix.append(row)

    n = len(matrix)
    for row in matrix:
        if len(row) != n:
            raise ValueError("Erro: a matriz deve ser quadrada!")
    return matrix


def pretty_print(M):
    for row in M:
        print("[" + ", ".join(str(x) for x in row) + "]")
    print()


def gauss_jordan_steps(A):
    M = deepcopy(A)
    n = len(M)
    steps = []

    steps.append("Início do escalonamento para testar invertibilidade:\n")
    steps.append("Critério: A matriz é invertível se TODOS os pivôs são não-nulos.\n"
                 "Ou seja, NENHUMA coluna de pivô fica sem pivô e NENHUMA linha vira zero.\n"
                 "Se faltar pivô → matriz NÃO é invertível.\n")

    for col in range(n):

        steps.append(f"--- Analisando coluna {col+1} (buscando pivô) ---")

        pivot_row = None
        for r in range(col, n):
            if M[r][col] != 0:
                pivot_row = r
                break

        if pivot_row is None:
            steps.append(f"❌ Não existe pivô na coluna {col+1}.")
            steps.append("⚠ Isso significa que o posto é menor que o tamanho da matriz.")
            steps.append("➡ Portanto, a matriz NÃO é invertível.\n")
            return steps, M, False

        if pivot_row != col:
            steps.append(f"↔ Trocando R{col+1} com R{pivot_row+1} para trazer pivô para cima.")
            M[col], M[pivot_row] = M[pivot_row], M[col]
            steps.append(deepcopy(M))

        pivot = M[col][col]
        if pivot != 1:
            steps.append(f"÷ Normalizando pivô: R{col+1} ← R{col+1} / {pivot}")
            M[col] = [x / pivot for x in M[col]]
            steps.append(deepcopy(M))

        for r in range(n):
            if r != col and M[r][col] != 0:
                f = M[r][col]
                steps.append(f"- Eliminando entrada abaixo/acima do pivô: R{r+1} ← R{r+1} - ({f}) * R{col+1}")
                M[r] = [M[r][c] - f * M[col][c] for c in range(n)]
                steps.append(deepcopy(M))

        steps.append(f"✔ Pivô da coluna {col+1} confirmado como não-nulo. Seguindo...\n")

    steps.append("✔ Todos os pivôs existem e são não-nulos.")
    steps.append("✔ Escalonamento levou à forma identidade.")
    steps.append("➡ Portanto, a matriz É invertível!\n")

    return steps, M, True


def main():
    print("\n=== CALCULADORA DE MATRIZ INVERTÍVEL (ESCALONAMENTO PASSO A PASSO) ===\n")

    A = read_matrix()
    print("\nMatriz inicial:")
    pretty_print(A)

    steps, finalM, invertible = gauss_jordan_steps(A)

    print("=== PASSO A PASSO ===\n")
    for s in steps:
        if isinstance(s, list):
            pretty_print(s)
        else:
            print(s)

    print("=== MATRIZ FINAL (REDUZIDA) ===")
    pretty_print(finalM)

    print("=== RESULTADO ===")
    if invertible:
        print("✅ A matriz é INVERTÍVEL porque TODOS os pivôs foram encontrados e nenhum virou zero.")
    else:
        print("❌ A matriz NÃO é invertível porque FALTOU pivô ou ocorreu linha nula.")
    print()


if __name__ == "__main__":
    main()



=== CALCULADORA DE MATRIZ INVERTÍVEL (ESCALONAMENTO PASSO A PASSO) ===

Digite a matriz linha por linha (somente números).
Exemplo:
1 2 3
0 1 4
5 6 0
Pressione ENTER em branco para terminar.

Linha: 3 2 1
Linha: 1 0 4
Linha: 2 5 6
Linha: 

Matriz inicial:
[3, 2, 1]
[1, 0, 4]
[2, 5, 6]

=== PASSO A PASSO ===

Início do escalonamento para testar invertibilidade:

Critério: A matriz é invertível se TODOS os pivôs são não-nulos.
Ou seja, NENHUMA coluna de pivô fica sem pivô e NENHUMA linha vira zero.
Se faltar pivô → matriz NÃO é invertível.

--- Analisando coluna 1 (buscando pivô) ---
÷ Normalizando pivô: R1 ← R1 / 3
[1, 2/3, 1/3]
[1, 0, 4]
[2, 5, 6]

- Eliminando entrada abaixo/acima do pivô: R2 ← R2 - (1) * R1
[1, 2/3, 1/3]
[0, -2/3, 11/3]
[2, 5, 6]

- Eliminando entrada abaixo/acima do pivô: R3 ← R3 - (2) * R1
[1, 2/3, 1/3]
[0, -2/3, 11/3]
[0, 11/3, 16/3]

✔ Pivô da coluna 1 confirmado como não-nulo. Seguindo...

--- Analisando coluna 2 (buscando pivô) ---
÷ Normalizando pivô: R2 ← R2

Escalonamento completo


In [21]:
from fractions import Fraction
from copy import deepcopy

def read_augmented_matrix():
    print("Digite a matriz aumentada (coeficientes + termos independentes).")
    print("Exemplo (3x3):")
    print("1 2 -1 3")
    print("2 -1 3 7")
    print("3 1 2 10")
    print("Pressione ENTER em branco para terminar.\n")

    M = []
    while True:
        line = input("Linha: ").strip()
        if line == "":
            break
        row = [Fraction(x) for x in line.split()]
        M.append(row)

    if len(M) == 0:
        raise ValueError("Matriz vazia!")

    n_cols = len(M[0])
    for row in M:
        if len(row) != n_cols:
            raise ValueError("Todas as linhas devem ter o mesmo número de colunas!")
    return M

def print_matrix(M):
    for row in M:
        print("[" + "  ".join(str(x) for x in row) + "]")
    print()

def gauss_jordan_solve(M):
    M = deepcopy(M)
    rows = len(M)
    cols = len(M[0])
    steps = []

    steps.append("Início do escalonamento Gauss-Jordan:\n")

    row = 0
    for col in range(cols-1):
        # Encontrar pivô
        pivot_row = None
        for r in range(row, rows):
            if M[r][col] != 0:
                pivot_row = r
                break

        if pivot_row is None:
            steps.append(f"⚠ Não há pivô na coluna {col+1}.")
            continue

        if pivot_row != row:
            steps.append(f"↔ Trocando linha {row+1} com linha {pivot_row+1}")
            M[row], M[pivot_row] = M[pivot_row], M[row]
            steps.append(deepcopy(M))

        pivot = M[row][col]
        steps.append(f"÷ Normalizando pivô da linha {row+1} (dividindo por {pivot})")
        M[row] = [x / pivot for x in M[row]]
        steps.append(deepcopy(M))

        # Eliminar todas as outras linhas na coluna
        for r in range(rows):
            if r != row and M[r][col] != 0:
                f = M[r][col]
                steps.append(f"- Eliminando elemento da linha {r+1}: R{r+1} ← R{r+1} - ({f})*R{row+1}")
                M[r] = [M[r][c] - f*M[row][c] for c in range(cols)]
                steps.append(deepcopy(M))

        row += 1
        if row >= rows:
            break

    # Analisar solução
    solution = []
    free_vars = []
    inconsistent = False

    for r in range(rows):
        left = M[r][:-1]
        rhs = M[r][-1]
        if all(x == 0 for x in left) and rhs != 0:
            inconsistent = True
            break
        elif all(x == 0 for x in left) and rhs == 0:
            free_vars.append(r)

    if inconsistent:
        steps.append("❌ Sistema impossível!")
        solution = None
    elif free_vars:
        steps.append("⚠ Sistema indeterminado (variáveis livres).")
        solution = None
    else:
        steps.append("✔ Sistema determinado, solução única encontrada:")
        solution = [M[r][-1] for r in range(rows)]

    return steps, M, solution

def main():
    print("\n=== CALCULADORA DE SISTEMA LINEAR (Gauss-Jordan Passo a Passo) ===\n")

    M = read_augmented_matrix()
    print("\nMatriz inicial:")
    print_matrix(M)

    steps, finalM, solution = gauss_jordan_solve(M)

    print("=== PASSO A PASSO ===\n")
    for s in steps:
        if isinstance(s, list):
            print_matrix(s)
        else:
            print(s)

    print("=== MATRIZ FINAL ===")
    print_matrix(finalM)

    print("=== SOLUÇÃO ===")
    if solution is None:
        print("O sistema é impossível ou indeterminado.")
    else:
        for i, val in enumerate(solution):
            print(f"x{i+1} = {val}")

if __name__ == "__main__":
    main()



=== CALCULADORA DE SISTEMA LINEAR (Gauss-Jordan Passo a Passo) ===

Digite a matriz aumentada (coeficientes + termos independentes).
Exemplo (3x3):
1 2 -1 3
2 -1 3 7
3 1 2 10
Pressione ENTER em branco para terminar.

Linha: 1 2 -1 3
Linha: 2 -1 3 7
Linha: 3 1 2 10
Linha: 

Matriz inicial:
[1  2  -1  3]
[2  -1  3  7]
[3  1  2  10]

=== PASSO A PASSO ===

Início do escalonamento Gauss-Jordan:

÷ Normalizando pivô da linha 1 (dividindo por 1)
[1  2  -1  3]
[2  -1  3  7]
[3  1  2  10]

- Eliminando elemento da linha 2: R2 ← R2 - (2)*R1
[1  2  -1  3]
[0  -5  5  1]
[3  1  2  10]

- Eliminando elemento da linha 3: R3 ← R3 - (3)*R1
[1  2  -1  3]
[0  -5  5  1]
[0  -5  5  1]

÷ Normalizando pivô da linha 2 (dividindo por -5)
[1  2  -1  3]
[0  1  -1  -1/5]
[0  -5  5  1]

- Eliminando elemento da linha 1: R1 ← R1 - (2)*R2
[1  0  1  17/5]
[0  1  -1  -1/5]
[0  -5  5  1]

- Eliminando elemento da linha 3: R3 ← R3 - (-5)*R2
[1  0  1  17/5]
[0  1  -1  -1/5]
[0  0  0  0]

⚠ Não há pivô na coluna 3.
⚠ S

Determinante por sarrus(até 3x3)


In [34]:
from fractions import Fraction

def sarrus_det(A):
    # A deve ser 3×3
    a, b, c = A[0]
    d, e, f = A[1]
    g, h, i = A[2]

    # Diagonais principais (3 produtos)
    dp1 = a*e*i
    dp2 = b*f*g
    dp3 = c*d*h

    # Diagonais secundárias (3 produtos)
    ds1 = c*e*g
    ds2 = b*d*i
    ds3 = a*f*h

    print("\n=== Regra de Sarrus ===\n")

    print("Diagonal principal:")
    print(f"{a}·{e}·{i} = {dp1}")
    print(f"{b}·{f}·{g} = {dp2}")
    print(f"{c}·{d}·{h} = {dp3}")
    print("Soma DP =", dp1 + dp2 + dp3)

    print("\nDiagonal secundária:")
    print(f"{c}·{e}·{g} = {ds1}")
    print(f"{b}·{d}·{i} = {ds2}")
    print(f"{a}·{f}·{h} = {ds3}")
    print("Soma DS =", ds1 + ds2 + ds3)

    det = (dp1 + dp2 + dp3) - (ds1 + ds2 + ds3)

    print("\nDeterminante = (Soma DP) – (Soma DS)")
    print("Determinante =", det)

    return det

print("=== Determinante pela Regra de Sarrus (3x3) ===")
print("Digite a matriz linha por linha:")

A = []
for i in range(3):
    linha = input(f"Linha {i+1}: ").split()
    A.append([Fraction(x) for x in linha])

sarrus_det(A)


=== Determinante pela Regra de Sarrus (3x3) ===
Digite a matriz linha por linha:
Linha 1: 2 -1 0
Linha 2: 1 3 2
Linha 3: 0 4 5

=== Regra de Sarrus ===

Diagonal principal:
2·3·5 = 30
-1·2·0 = 0
0·1·4 = 0
Soma DP = 30

Diagonal secundária:
0·3·0 = 0
-1·1·5 = -5
2·2·4 = 16
Soma DS = 11

Determinante = (Soma DP) – (Soma DS)
Determinante = 19


Fraction(19, 1)

Determinante por laplace

In [42]:
def ler_matriz():
    print("Digite a matriz quadrada (linha por linha, separados por espaço).")
    print("Deixe em branco para encerrar.\n")

    M = []
    while True:
        linha = input(f"Linha {len(M)+1}: ").strip()
        if linha == "":
            break
        M.append([float(x) for x in linha.split()])

    # Verifica se é quadrada
    n = len(M)
    for row in M:
        if len(row) != n:
            raise ValueError("A matriz deve ser quadrada.")
    return M


def minor_matrix(M, i, j):
    return [linha[:j] + linha[j+1:] for k, linha in enumerate(M) if k != i]


def det_laplace(M, nivel=0):
    n = len(M)
    indent = "  " * nivel

    # Caso base 1x1
    if n == 1:
        print(f"{indent}Determinante 1x1 = {M[0][0]}")
        return M[0][0]

    # Caso base 2x2
    if n == 2:
        det2 = M[0][0]*M[1][1] - M[0][1]*M[1][0]
        print(f"{indent}Det 2x2 = {M[0][0]}*{M[1][1]} - {M[0][1]}*{M[1][0]} = {det2}")
        return det2

    print(f"{indent}Expansão de Laplace pela 1ª linha:")
    print(f"{indent}Linha considerada: {M[0]}\n")

    soma_termos = []
    resultado = 0

    for j in range(n):
        sinal = (-1)**j
        a = M[0][j]
        menor = minor_matrix(M, 0, j)

        print(f"{indent}Cofator C(1,{j+1}):")
        print(f"{indent}  Fórmula: C(1,{j+1}) = (-1)^({1}+{j+1}) · a(1,{j+1}) · det(M(1,{j+1}))")
        print(f"{indent}  -> (-1)^({1+j+1}) = {sinal}")
        print(f"{indent}  -> a(1,{j+1}) = {a}")
        print(f"{indent}  -> Matriz menor M(1,{j+1}) = {menor}")

        det_menor = det_laplace(menor, nivel+1)

        termo = sinal * a * det_menor
        resultado += termo

        print(f"{indent}  Termo do cofator = {sinal} * {a} * {det_menor} = {termo}\n")

        soma_termos.append(f"{sinal}·{a}·({det_menor})")

    # Mostrar expressão final do determinante
    if nivel == 0:
        print("\nEXPRESSÃO FINAL DO DETERMINANTE:")
        print("det(A) =", " + ".join(soma_termos))
        print("det(A) =", resultado)

    return resultado


# ------------------------------
#   Programa principal
# ------------------------------

print("==== Determinante pelo Método de Laplace ====\n")
A = ler_matriz()

print("\nCalculando determinante...\n")
resultado = det_laplace(A)

print("\n>>> RESULTADO FINAL =", resultado)


==== Determinante pelo Método de Laplace ====

Digite a matriz quadrada (linha por linha, separados por espaço).
Deixe em branco para encerrar.

Linha 1: 1 2 3
Linha 2: 2 5 7
Linha 3: 1 3 4
Linha 4: 

Calculando determinante...

Expansão de Laplace pela 1ª linha:
Linha considerada: [1.0, 2.0, 3.0]

Cofator C(1,1):
  Fórmula: C(1,1) = (-1)^(1+1) · a(1,1) · det(M(1,1))
  -> (-1)^(2) = 1
  -> a(1,1) = 1.0
  -> Matriz menor M(1,1) = [[5.0, 7.0], [3.0, 4.0]]
  Det 2x2 = 5.0*4.0 - 7.0*3.0 = -1.0
  Termo do cofator = 1 * 1.0 * -1.0 = -1.0

Cofator C(1,2):
  Fórmula: C(1,2) = (-1)^(1+2) · a(1,2) · det(M(1,2))
  -> (-1)^(3) = -1
  -> a(1,2) = 2.0
  -> Matriz menor M(1,2) = [[2.0, 7.0], [1.0, 4.0]]
  Det 2x2 = 2.0*4.0 - 7.0*1.0 = 1.0
  Termo do cofator = -1 * 2.0 * 1.0 = -2.0

Cofator C(1,3):
  Fórmula: C(1,3) = (-1)^(1+3) · a(1,3) · det(M(1,3))
  -> (-1)^(4) = 1
  -> a(1,3) = 3.0
  -> Matriz menor M(1,3) = [[2.0, 5.0], [1.0, 3.0]]
  Det 2x2 = 2.0*3.0 - 5.0*1.0 = 1.0
  Termo do cofator = 1 * 3.0

Vetores: Linearmente Dependente e independente

In [49]:
from fractions import Fraction

def ler_vetores():
    print("Digite cada vetor (um por linha), números separados por espaço.")
    print("Exemplo para vetores em R^3: 1 2 3")
    print("Deixe a linha vazia para terminar.\n")

    vet = []
    while True:
        linha = input(f"Vetor {len(vet)+1}: ").strip()
        if linha == "":
            break
        vet.append([Fraction(x) for x in linha.split()])

    if not vet:
        raise ValueError("Nenhum vetor informado.")
    # checar dimensões iguais
    dim = len(vet[0])
    for v in vet:
        if len(v) != dim:
            raise ValueError("Todos os vetores devem ter a mesma dimensão.")
    return vet

def montar_matriz_colunas(vetores):
    """Retorna matriz (lista de linhas) cuja cada coluna é um vetor."""
    return [list(col) for col in zip(*vetores)]

def pretty_matrix(M):
    """Formata matriz (lista de linhas) para impressão alinhada."""
    widths = []
    cols = len(M[0])
    for j in range(cols):
        w = 0
        for i in range(len(M)):
            s = str(M[i][j])
            if len(s) > w: w = len(s)
        widths.append(w)
    lines = []
    for row in M:
        items = [str(row[j]).rjust(widths[j]) for j in range(cols)]
        lines.append("[ " + "  ".join(items) + " ]")
    return "\n".join(lines)

def det_2x2(M, passo=True):
    a,b = M[0]
    c,d = M[1]
    det = a*d - b*c
    if passo:
        print(f"\nDeterminante 2×2: ({a})·({d}) - ({b})·({c}) = {det}")
    return det

def det_3x3_sarrus(M, passo=True):
    a,b,c = M[0]
    d,e,f = M[1]
    g,h,i = M[2]
    dp1 = a*e*i; dp2 = b*f*g; dp3 = c*d*h
    ds1 = c*e*g; ds2 = b*d*i; ds3 = a*f*h
    if passo:
        print("\n=== Regra de Sarrus (3×3) ===")
        print("Diagonal principal:")
        print(f"{a}·{e}·{i} = {dp1}")
        print(f"{b}·{f}·{g} = {dp2}")
        print(f"{c}·{d}·{h} = {dp3}")
        print("Soma DP =", dp1+dp2+dp3)
        print("\nDiagonal secundária:")
        print(f"{c}·{e}·{g} = {ds1}")
        print(f"{b}·{d}·{i} = {ds2}")
        print(f"{a}·{f}·{h} = {ds3}")
        print("Soma DS =", ds1+ds2+ds3)
    det = (dp1+dp2+dp3) - (ds1+ds2+ds3)
    if passo:
        print("\nDeterminante 3×3 =", det)
    return det

def minor_matrix(M, i, j):
    return [row[:j] + row[j+1:] for r,row in enumerate(M) if r != i]

def det_laplace(M, nivel=0):
    n = len(M)
    indent = "  " * nivel
    if n == 1:
        if nivel==0: print(f"Det 1×1 = {M[0][0]}")
        return M[0][0]
    if n == 2:
        return det_2x2(M, passo=(nivel==0))
    print(f"{indent}Expansão de Laplace pela 1ª linha: {M[0]}")
    total = Fraction(0)
    for j in range(n):
        a = M[0][j]
        sinal = (-1) ** j
        menor = minor_matrix(M, 0, j)
        print(f"{indent}Cofator C(1,{j+1}): sinal={sinal}, a(1,{j+1})={a}")
        print(f"{indent}Menor M(1,{j+1}) = {menor}")
        det_menor = det_laplace(menor, nivel+1)
        termo = sinal * a * det_menor
        print(f"{indent}Termo = {sinal} * {a} * {det_menor} = {termo}\n")
        total += termo
    if nivel == 0:
        print(f"Determinante (Laplace) = {total}")
    return total

def calcular_determinante(M):
    n = len(M)
    if any(len(row) != n for row in M):
        raise ValueError("Determinante só definido para matriz quadrada.")
    if n == 1: return M[0][0]
    if n == 2: return det_2x2(M)
    if n == 3: return det_3x3_sarrus(M)
    return det_laplace(M)

# Programa principal
vetores = ler_vetores()
A = montar_matriz_colunas(vetores)

print("\n=== Matriz montada (vetores como COLUNAS) ===")
print(pretty_matrix(A))

# Verificação: quadratura
n_rows = len(A)
n_cols = len(A[0])
if n_rows != n_cols:
    print("\nA matriz NÃO é quadrada ({}×{}).".format(n_rows, n_cols))
    print("Como o número de vetores e a dimensão não formam matriz quadrada, não é possível calcular determinante.")
    print("Nesse caso, os vetores são necessariamente linearmente dependentes (mais vetores que a dimensão) ou não formam base completa.")
else:
    print("\n=== Cálculo do determinante (sem escalonamento) ===")
    det = calcular_determinante(A)
    print("\nDeterminante =", det)
    if det == 0:
        print("\n➡️ Como o determinante é ZERO, os vetores são LINEARMENTE DEPENDENTES.")
    else:
        print("\n➡️ Como o determinante é NÃO ZERO, os vetores são LINEARMENTE INDEPENDENTES.")


Digite cada vetor (um por linha), números separados por espaço.
Exemplo para vetores em R^3: 1 2 3
Deixe a linha vazia para terminar.

Vetor 1: 1 2 1
Vetor 2: 2 5 3
Vetor 3: 3 7 4
Vetor 4: 

=== Matriz montada (vetores como COLUNAS) ===
[ 1  2  3 ]
[ 2  5  7 ]
[ 1  3  4 ]

=== Cálculo do determinante (sem escalonamento) ===

=== Regra de Sarrus (3×3) ===
Diagonal principal:
1·5·4 = 20
2·7·1 = 14
3·2·3 = 18
Soma DP = 52

Diagonal secundária:
3·5·1 = 15
2·2·4 = 16
1·7·3 = 21
Soma DS = 52

Determinante 3×3 = 0

Determinante = 0

➡️ Como o determinante é ZERO, os vetores são LINEARMENTE DEPENDENTES.


In [7]:
from fractions import Fraction

# ----------------------------------------------------------
# FUNÇÃO PARA LER 3 VETORES
# ----------------------------------------------------------
def ler_vetores():
    print("Digite os vetores v1, v2 e v3 (3 números por linha):")
    vetores = []
    for i in range(3):
        linha = input(f"v{i+1}: ").split()
        vetores.append([Fraction(x) for x in linha])
    return vetores


# ----------------------------------------------------------
# FUNÇÃO PARA MONTAR MATRIZ (vetores como COLUNAS)
# ----------------------------------------------------------
def montar_matriz(v):
    print("\n=== MATRIZ FORMADA (VETORES COMO COLUNAS) ===")
    M = [
        [v[0][0], v[1][0], v[2][0]],
        [v[0][1], v[1][1], v[2][1]],
        [v[0][2], v[1][2], v[2][2]]
    ]
    for linha in M:
        print(linha)
    return M


# ----------------------------------------------------------
# DETERMINANTE (SARRUS) COM PASSO A PASSO
# ----------------------------------------------------------
def determinante_3x3(M):
    a,b,c = M[0]
    d,e,f = M[1]
    g,h,i = M[2]

    print("\n=== CÁLCULO DO DETERMINANTE (Regra de Sarrus) ===")
    print("det = aei + bfg + cdh – (ceg + bdi + afh)")
    print(f"det = ({a}*{e}*{i}) + ({b}*{f}*{g}) + ({c}*{d}*{h}) - "
          f"[({c}*{e}*{g}) + ({b}*{d}*{i}) + ({a}*{f}*{h})]")

    det = (a*e*i + b*f*g + c*d*h) - (c*e*g + b*d*i + a*f*h)
    print(f"det = {det}\n")
    return det


# ----------------------------------------------------------
# RELAÇÃO DE DEPENDÊNCIA LINEAR — PASSO A PASSO
# Resolve a·v1 + b·v2 + c·v3 = 0
# ----------------------------------------------------------
def relacao_dependencia(v):
    print("\n=== RELAÇÃO DE DEPENDÊNCIA LINEAR ===")

    # Sistema:
    # a*v1 + b*v2 + c*v3 = 0
    print("\nMontando equações:")
    print("a·v1 + b·v2 + c·v3 = 0\n")

    print("Equações linha por linha:\n")

    # Cada linha vira:
    # a*v1[i] + b*v2[i] + c*v3[i] = 0
    eqs = []
    for i in range(3):
        eqs.append([v[0][i], v[1][i], v[2][i]])
        print(f"{v[0][i]}·a + {v[1][i]}·b + {v[2][i]}·c = 0")

    print("\nAgora vamos resolver o sistema.\n")
    print("Escolhemos c = 1 (parâmetro livre, pois o sistema é dependente).")

    c = Fraction(1)

    # Resolver as equações manualmente:
    # Usaremos eliminação direta para mostrar os passos

    a1, b1, c1 = eqs[0]
    a2, b2, c2 = eqs[1]
    a3, b3, c3 = eqs[2]

    print("\nSubstituindo c = 1 nas três equações:")

    print(f"{a1}·a + {b1}·b = {-c1}")
    print(f"{a2}·a + {b2}·b = {-c2}")
    print(f"{a3}·a + {b3}·b = {-c3}\n")

    # Usamos as duas primeiras equações
    # Resolver sistema 2x2
    D = a1*b2 - a2*b1

    if D != 0:
        a = ((-c1)*b2 - (-c2)*b1) / D
        b = (a1*(-c2) - a2*(-c1)) / D
    else:
        # fallback quando duas equações são múltiplas
        b = Fraction(1)
        a = -(b1*b + c1) / a1 if a1 != 0 else 0

    print("Resolvendo o sistema 2x2 para a e b:")
    print(f"a = {a}")
    print(f"b = {b}")

    print("\n=== Relação Final ===")
    print(f"{a}·v1 + {b}·v2 + {c}·v3 = 0\n")

    return a, b, c


# ----------------------------------------------------------
# PROGRAMA PRINCIPAL
# ----------------------------------------------------------
def main():
    vetores = ler_vetores()
    M = montar_matriz(vetores)
    det = determinante_3x3(M)

    if det != 0:
        print("Como o determinante é diferente de zero, os vetores são LINEARMENTE INDEPENDENTES.")
    else:
        print("Como o determinante é zero, os vetores são LINEARMENTE DEPENDENTES.")
        relacao_dependencia(vetores)


main()


Digite os vetores v1, v2 e v3 (3 números por linha):
v1: 1 2 0 1
v2: 2 1 4 3
v3: 3 1 6 4

=== MATRIZ FORMADA (VETORES COMO COLUNAS) ===
[Fraction(1, 1), Fraction(2, 1), Fraction(3, 1)]
[Fraction(2, 1), Fraction(1, 1), Fraction(1, 1)]
[Fraction(0, 1), Fraction(4, 1), Fraction(6, 1)]

=== CÁLCULO DO DETERMINANTE (Regra de Sarrus) ===
det = aei + bfg + cdh – (ceg + bdi + afh)
det = (1*1*6) + (2*1*0) + (3*2*4) - [(3*1*0) + (2*2*6) + (1*1*4)]
det = 2

Como o determinante é diferente de zero, os vetores são LINEARMENTE INDEPENDENTES.


,m


In [6]:
from fractions import Fraction
from copy import deepcopy
from math import gcd

# -------------------- utilidades de impressão --------------------
def pretty_matrix(M):
    if not M: return "[]"
    rows = [[str(x) for x in row] for row in M]
    cols = len(rows[0])
    colw = [max(len(rows[r][c]) for r in range(len(rows))) for c in range(cols)]
    lines = []
    for i, row in enumerate(rows):
        items = [row[j].rjust(colw[j]) for j in range(cols)]
        lines.append("[ " + "  ".join(items) + " ]")
    return "\n".join(lines)

def print_row_op(msg):
    print(msg)

# -------------------- leitura de vetores (qualquer dimensão) --------------------
def ler_vetores():
    print("Digite vetores, um por linha (componentes separados por espaço).")
    print("Pressione ENTER em branco para terminar (deve haver pelo menos 2 vetores).\n")
    vet = []
    dim = None
    while True:
        s = input(f"v{len(vet)+1}: ").strip()
        if s == "":
            break
        parts = s.split()
        if dim is None:
            dim = len(parts)
            if dim == 0:
                print("Digite pelo menos um número.")
                continue
        if len(parts) != dim:
            print(f"Todos os vetores devem ter {dim} componentes. Tente novamente.")
            continue
        try:
            vec = [Fraction(x) for x in parts]
        except Exception:
            print("Entrada inválida — use números inteiros, decimais ou frações (ex: 1/2).")
            continue
        vet.append(vec)
    if len(vet) < 2:
        raise SystemExit("É preciso informar ao menos 2 vetores.")
    return vet

# -------------------- monta matriz com vetores como colunas --------------------
def montar_matriz_colunas(vetores):
    n = len(vetores[0])   # dimensão
    m = len(vetores)      # número de vetores (colunas)
    A = [[vetores[j][i] for j in range(m)] for i in range(n)]
    return A

# -------------------- montar matriz aumentada do sistema homogêneo A·x = 0 --------------------
def montar_aumentada_homogeneo(A):
    # A é n x m (n linhas, m colunas). Queremos matriz aumentada n x (m+1) com última coluna 0
    n = len(A); m = len(A[0])
    Aug = [A[i] + [Fraction(0)] for i in range(n)]
    return Aug

# -------------------- Gauss-Jordan passo a passo --------------------
def gauss_jordan_passos(Aug):
    M = deepcopy(Aug)
    n = len(M); m = len(M[0])  # m = num_variaveis + 1
    num_vars = m - 1
    pivot_row = 0
    pivot_positions = []  # (row, col)
    print("\nMatriz aumentada inicial:")
    print(pretty_matrix(M))

    for col in range(num_vars):
        # encontrar linha pivot com valor não-zero na coluna col a partir de pivot_row
        pivot = None
        for r in range(pivot_row, n):
            if M[r][col] != 0:
                pivot = r
                break
        if pivot is None:
            print(f"\nColuna {col+1}: nenhum pivô encontrado (coluna livre).")
            continue

        # trocar se necessário
        if pivot != pivot_row:
            print(f"\nTroca L{pivot_row+1} <-> L{pivot+1}")
            M[pivot_row], M[pivot] = M[pivot], M[pivot_row]
            print(pretty_matrix(M))

        # normalizar pivô para 1
        pv = M[pivot_row][col]
        if pv != 1:
            print(f"\nDividindo L{pivot_row+1} por {pv} para tornar pivô 1")
            M[pivot_row] = [x / pv for x in M[pivot_row]]
            print(pretty_matrix(M))

        # zerar outras linhas na coluna col
        for r in range(n):
            if r == pivot_row:
                continue
            factor = M[r][col]
            if factor != 0:
                print(f"\nL{r+1} = L{r+1} - ({factor})·L{pivot_row+1}")
                M[r] = [M[r][c] - factor * M[pivot_row][c] for c in range(m)]
                print(pretty_matrix(M))

        pivot_positions.append((pivot_row, col))
        pivot_row += 1
        if pivot_row == n:
            break

    print("\nMatriz após Gauss-Jordan (RREF parcial/completa):")
    print(pretty_matrix(M))
    return M, pivot_positions

# -------------------- extrair relação de dependência com passo a passo --------------------
def relacao_dependencia_passos(R, pivot_positions, num_vars):
    n = len(R)
    m = num_vars
    piv_cols = [col for (_, col) in pivot_positions]
    free_vars = [j for j in range(m) if j not in piv_cols]

    print("\nPivôs (colunas):", piv_cols)
    print("Variáveis livres:", free_vars)

    if not free_vars:
        print("\nNão há variáveis livres → só solução trivial → vetores INDEPENDENTES.")
        return None

    # vamos construir solução paramétrica com parâmetros t1, t2, ...
    # aqui escolhemos cada variável livre como parâmetro; para simplicidade atribuímos 1 ao primeiro livre e 0 aos outros
    sol = [Fraction(0)] * m
    free = free_vars[0]
    sol[free] = Fraction(1)
    print(f"\nEscolhemos x{free+1} = 1 (parâmetro). As outras variáveis livres = 0 por escolha.")
    # mostrar equações correspondentes às linhas com pivô:
    # para cada linha i com pivô na coluna j: x_j + sum_{k>j} R[i][k]*x_k = 0  (já RREF)
    for (r, c) in pivot_positions:
        rhs = -R[r][m]  # termo constante (0)
        soma = Fraction(0)
        expr_parts = []
        for k in range(c+1, m):
            coeff = R[r][k]
            if coeff != 0:
                expr_parts.append(f"({coeff})·x{k+1}")
                soma += coeff * sol[k]
        # x_c = - suma - termo_constante
        print(f"\nLinha com pivô L{r+1}: x{c+1} + " +
              (" + ".join(expr_parts) if expr_parts else "0") +
              f" = 0  → x{c+1} = -({ ' + '.join(expr_parts) if expr_parts else '0' })")
        # calcular numeric
        numeric = -soma - rhs
        sol[c] = numeric
        print(f"Substituindo valores atuais das livres: x{c+1} = {numeric}")

    print("\nSolução paramétrica (frações):")
    for i, val in enumerate(sol, 1):
        print(f"x{i} = {val}")

    # simplificar para inteiros proporcionais: multiplica por lcm dos denominadores
    dens = [val.denominator for val in sol if val != 0]
    if dens:
        def lcm(a,b): return a*b // gcd(a,b)
        L = 1
        for d in dens:
            L = lcm(L, d)
        ints = [int(val * L) for val in sol]
        # simplificar por gcd de todos inteiros não-zero
        g = 0
        for v in ints:
            if v != 0:
                g = abs(v) if g == 0 else gcd(g, abs(v))
        if g == 0: g = 1
        simp = [v//g for v in ints]
        print("\nForma inteira proporcional (multiplicada por LCM dos denominadores e simplificada):")
        print(simp)
        # imprimir relação final
        terms = []
        for idx, coeff in enumerate(simp):
            if coeff == 0: continue
            terms.append(f"({coeff})·v{idx+1}")
        relation = " + ".join(terms) + " = 0"
        print("\nRelação de dependência linear (final, forma inteira e simples):")
        print(relation)
        return simp
    else:
        print("\nTodas as componentes da solução são zero (improvável aqui).")
        return None

# -------------------- MAIN --------------------
def main():
    vet = ler_vetores()
    print("\nVetores lidos:")
    for i, v in enumerate(vet, 1):
        print(f"v{i} = {v}")

    A = montar_matriz_colunas(vet)
    print("\nMatriz A (vetores como COLUNAS):")
    print(pretty_matrix(A))

    Aug = montar_aumentada_homogeneo(A)
    print("\nMatriz aumentada do sistema homogêneo A·x = 0:")
    print(pretty_matrix(Aug))

    R, pivot_positions = gauss_jordan_passos(Aug)
    num_vars = len(A[0])
    rel = relacao_dependencia_passos(R, pivot_positions, num_vars)
    if rel is None and pivot_positions:
        # caso: sem variáveis livres → independentes
        pass

if __name__ == "__main__":
    main()


Digite vetores, um por linha (componentes separados por espaço).
Pressione ENTER em branco para terminar (deve haver pelo menos 2 vetores).

v1: 1 2 0 1
v2: 2 1 4 3
v3: 3 1 6 4
v4: 

Vetores lidos:
v1 = [Fraction(1, 1), Fraction(2, 1), Fraction(0, 1), Fraction(1, 1)]
v2 = [Fraction(2, 1), Fraction(1, 1), Fraction(4, 1), Fraction(3, 1)]
v3 = [Fraction(3, 1), Fraction(1, 1), Fraction(6, 1), Fraction(4, 1)]

Matriz A (vetores como COLUNAS):
[ 1  2  3 ]
[ 2  1  1 ]
[ 0  4  6 ]
[ 1  3  4 ]

Matriz aumentada do sistema homogêneo A·x = 0:
[ 1  2  3  0 ]
[ 2  1  1  0 ]
[ 0  4  6  0 ]
[ 1  3  4  0 ]

Matriz aumentada inicial:
[ 1  2  3  0 ]
[ 2  1  1  0 ]
[ 0  4  6  0 ]
[ 1  3  4  0 ]

L2 = L2 - (2)·L1
[ 1   2   3  0 ]
[ 0  -3  -5  0 ]
[ 0   4   6  0 ]
[ 1   3   4  0 ]

L4 = L4 - (1)·L1
[ 1   2   3  0 ]
[ 0  -3  -5  0 ]
[ 0   4   6  0 ]
[ 0   1   1  0 ]

Dividindo L2 por -3 para tornar pivô 1
[ 1  2    3  0 ]
[ 0  1  5/3  0 ]
[ 0  4    6  0 ]
[ 0  1    1  0 ]

L1 = L1 - (2)·L2
[ 1  0  -1/3  0 ]

Inversa


In [10]:
from fractions import Fraction

# =======================
# Função para imprimir matriz bonita
# =======================
def print_matrix(M, title=""):
    if title:
        print("\n" + title)

    # descobrir largura de cada coluna
    col_widths = []
    for col in zip(*M):
        col_width = max(len(str(x)) for x in col)
        col_widths.append(col_width)

    # borda superior
    print("┌ " + "   ".join(" " * w for w in col_widths) + " ┐")

    # linhas da matriz
    for row in M:
        linha = []
        for i, val in enumerate(row):
            linha.append(str(val).rjust(col_widths[i]))
        print("│ " + "   ".join(linha) + " │")

    # borda inferior
    print("└ " + "   ".join(" " * w for w in col_widths) + " ┘\n")


# =======================
# Gauss-Jordan para inversa
# =======================
def gauss_jordan_inverse(A):
    n = len(A)

    # converter para Fractions
    A = [[Fraction(x) for x in row] for row in A]

    # matriz identidade
    I = [[Fraction(1 if i == j else 0) for j in range(n)] for i in range(n)]

    # matriz aumentada
    aug = [A[i] + I[i] for i in range(n)]
    print_matrix(aug, "Matriz aumentada inicial [A | I]:")

    # Gauss-Jordan
    for i in range(n):

        # pivô
        piv = aug[i][i]
        if piv == 0:
            # tentar troca de linha
            for k in range(i+1, n):
                if aug[k][i] != 0:
                    print(f"Trocando L{i+1} ↔ L{k+1}")
                    aug[i], aug[k] = aug[k], aug[i]
                    print_matrix(aug, "Após troca de linha:")
                    piv = aug[i][i]
                    break
            else:
                print("❌ Matriz não possui inversa (pivô zero).")
                return None

        # normalizar pivô
        print(f"Normalizando L{i+1} dividindo por {piv}")
        aug[i] = [x / piv for x in aug[i]]
        print_matrix(aug, f"Linha {i+1} normalizada:")

        # zerar outras linhas
        for k in range(n):
            if k != i:
                fator = aug[k][i]
                if fator != 0:
                    print(f"L{k+1} ← L{k+1} - ({fator})·L{i+1}")
                    aug[k] = [aug[k][j] - fator * aug[i][j] for j in range(2*n)]
                    print_matrix(aug, "Após operação:")

    # extrair inversa
    inversa = [row[n:] for row in aug]
    return inversa


# =======================
# Programa principal
# =======================
print("Digite uma matriz quadrada, linha por linha.")
print("(Aperte ENTER em branco para terminar.)\n")

A = []
while True:
    linha = input(f"Linha {len(A)+1}: ").strip()
    if linha == "":
        break
    A.append([Fraction(x) for x in linha.split()])

n = len(A)
if not all(len(l) == n for l in A):
    print("\n❌ ERRO: Matriz deve ser quadrada.")
else:
    inv = gauss_jordan_inverse(A)
    if inv is not None:
        print_matrix(inv, "✔ MATRIZ INVERSA (bonita e exata):")
1

Digite uma matriz quadrada, linha por linha.
(Aperte ENTER em branco para terminar.)

Linha 1: 2 -1 0
Linha 2: 1 3 2
Linha 3: 0 4 5
Linha 4: 

Matriz aumentada inicial [A | I]:
┌                        ┐
│ 2   -1   0   1   0   0 │
│ 1    3   2   0   1   0 │
│ 0    4   5   0   0   1 │
└                        ┘

Normalizando L1 dividindo por 2

Linha 1 normalizada:
┌                            ┐
│ 1   -1/2   0   1/2   0   0 │
│ 1      3   2     0   1   0 │
│ 0      4   5     0   0   1 │
└                            ┘

L2 ← L2 - (1)·L1

Após operação:
┌                             ┐
│ 1   -1/2   0    1/2   0   0 │
│ 0    7/2   2   -1/2   1   0 │
│ 0      4   5      0   0   1 │
└                             ┘

Normalizando L2 dividindo por 7/2

Linha 2 normalizada:
┌                                 ┐
│ 1   -1/2     0    1/2     0   0 │
│ 0      1   4/7   -1/7   2/7   0 │
│ 0      4     5      0     0   1 │
└                                 ┘

L1 ← L1 - (-1/2)·L2

Após operação:
┌         